version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: gig_tracker_postgres
    environment:
      POSTGRES_DB: GigTrackerDatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gig_tracker_network

volumes:
  postgres_data:

networks:
  gig_tracker_network:
    driver: bridge